#!/bin/sh

make latexpdf

sed ':a;N;$!ba;s/\.png}\n\n\\no/\.png}\n\\no/g' ./build/latex/BudgetBlitz.tex > ./build/latex/BudgetBlitz-manual.tex

cd ./build/latex
pdflatex -synctex=1 -interaction=nonstopmode ./BudgetBlitz-manual.tex
#Чтобы подставились номера страниц
pdflatex -synctex=1 -interaction=nonstopmode ./BudgetBlitz-manual.tex

evince ./BudgetBlitz-manual.pdf
